---

- name: Clean apt cache
  command: apt-get clean
  when: ansible_os_family == 'Debian'

- name: Clean yum cache
  command: yum clean all
  when: ansible_os_family == 'RedHat'

- name: Delete pip cache
  file:
    path: "{{ pip_cache_dir }}"
    state: absent